[workspace]
authors = ["Sergey Mikhno <sergey.mikhno@gmail.com>"]
channels = ["conda-forge"]
name = "doc-layout"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build-apk = "flet build apk --arch arm64-v8a --yes"

[dependencies]
python = "3.12.*"
pip = ">=25.0,<26"
pixi-pycharm = ">=0.0.10,<0.0.11"
pillow = ">=12.2.0,<13"

[pypi-dependencies]
flet = { version = ">=0.84.0,<1", extras = ["cli"] }
numpy = ">=1.26,<3"
opencv-python = ">=4.10,<5"
